### ISSUE TITLE
Use base64-encoded data URIs for displaying content to allow native interaction

### ISSUE THREAD

**Issue by justjanne** [Upload/Up1#32] opened 2015-08-13 18:38 UTC
**Expected behaviour:**  
I can right-click on any image, audio file, video, etc and open it in a new tab, save it in different places, etc. The files behave as if they were natively accessed directly over HTTP.

**Actual behaviour:**  
Right-clicking does not allow downloading, accessing or otherwise interacting with the files, the files can not be opened in a new tab

**Suggested solution:**  
Try to emulate native behaviour by using native widgets, for this use base64-encoded data URIs.

**Comment by ultramancool** [comment] 2015-08-13 18:42
You can do this... it works for me in Firefox at least.

**Comment by ultramancool** [comment] 2015-08-13 18:43
What browser are you using? We currently use blob URLs but this appears to allow native behavior in Chrome and Firefox at least.

**Comment by justjanne** [comment] 2015-08-13 19:38
Does not work in Firefox for me. I can right-click, but "view image" or "save as" do nothing.

**Comment by ultramancool** [comment] 2015-08-13 19:47
@justjanne Very strange. Both work for me. 

One small note is that the default Firefox image viewer looks quite similar to the one in Up1, if you do right click -> view image you should notice that the header and buttons vanish and the URL should change to a blob URL like blob:https://up1.ca/bff7d92e-cfae-42f3-b482-14781f474e5a. 

Save as also appears working on Firefox 40 running on Windows 10 and Ubuntu. What version of Firefox are you running and do you have any extensions installed that may affect this?

**Comment by justjanne** [comment] 2015-08-13 20:03
Currently running Firefox 40 on Arch Linux, no extensions enabled that can interfere.

I am sure it is not the default viewer, as the download button, etc still stay.

**Comment by ultramancool** [comment] 2015-08-13 20:34
Using the latest dev edition build (41.0a2) on Windows it appears to be working. Could you try a clean profile or something? I've been running this by other Firefox users and no one has been able to duplicate it yet.

> "view image info" reports a 0x0px PNG image

That view image info behavior is actually normal in Firefox apparently, I guess the View Image Info thing doesn't have access to the blob where the image is created. However, save and view image do still work on clean Firefox installs. Even if you save the image from the view image info dialog it does appear to work (though it won't get a very useful filename).

**Comment by justjanne** [comment] 2015-08-13 20:44
It just doesn’t even show the save image dialog – I can press the menu option and nothing happens. I just tested on a different computer running Ubuntu with a clean firefox profile, same issue.

**Comment by andre-d** [comment] 2015-08-13 22:03
Which Firefox version?

**Comment by ultramancool** [comment] 2015-08-13 22:04
@andre-d That was answered a while ago, read the whole thread. Unless you can duplicate this, I'm going to close as unable to reproduce. I've had 4 people independently test this and fail to reproduce the problem so far.

**Comment by andre-d** [comment] 2015-08-13 22:05
Sorry, 40, I see now.  And you are sure you have no extension? Embeds are
accessed as blob URLs which browsers should treat totally natively.

If the browser shows the button and it is not disabled then it should work
correctly so I am puzzled as to what would cause that.

**Comment by andre-d** [comment] 2015-08-14 01:11
I can not duplicate this issue no matter how hard I try on various machines and various browsers (including Linux machines).  If you believe you have found a Firefox issue please file one with their bug tracker, but as we're unable to duplicate this, we're unable to file it with them. I have had multiple folks on multiple setups unable to replicate this issue.

Blob URLs are the perfect solution for this designed to do exactly what we are doing (access typed arrays via regular browser interaction with a mime type anywhere a URL is required) compared to the hack that base64 data URIs are.  Blob URLs do not require us to duplicate memory away from the typed arrays and work properly on files of large sizes. Switching to base64'd data URIs would greatly impact performance.

It sounds like your blob is expiring or invalidating in some other way, but I can not figure out why it would do that, I tried leaving a tab open for hours while doing many other operations even and was still able to save. Is it possible your system is low on memory or disk space for cache? Even if that's the situation, it would be a Firefox bug, not an Up1 issue and to my knowledge Firefox does not invalidate blobs unless you navigate away from the page which created them. 

As such, I'm closing this as cannot reproduce unless someone can find a reliable way to cause this.

**Closed by andre-d** 2015-08-14 01:11 UTC
