### ISSUE TITLE
File not found or corrupt

### ISSUE THREAD

**Issue by GGMethos** [Upload/Up1#7] opened 2015-06-24 16:53 UTC
File not found or corrupt for every single thing uploaded

**Comment by k3d3** [comment] 2015-06-24 16:58
Is this on up1.ca or on your own instance?

If the latter, a few things to check:

1) Does the api_key match in server.conf and config.js?

2) does config.js exist (did you move config.js.example to config.js)?

**Comment by andre-d** [comment] 2015-06-24 16:58
An issue should be created for the fact that an error handler is missing for on upload and it just plows through as if it uploaded and displays you the preview anyway.

**Comment by k3d3** [comment] 2015-06-24 16:59
That's a good point too - we do need that

**Comment by k3d3** [comment] 2015-06-25 05:13
@GGMethos is there any other information you can add to this? As we can't reproduce this, we'll be closing this if you don't. Thanks

**Comment by GGMethos** [comment] 2015-06-25 06:53
For my own instance.



1) Does the api_key match in server.conf and config.js?

2) does config.js exist (did you move config.js.example to config.js)?

after double checking to make sure these things did in fact work, the problem still occurs.

**Comment by GGMethos** [comment] 2015-06-25 07:01
now after restarting the server five times it seems to be working. odd.

**Comment by k3d3** [comment] 2015-06-25 14:08
Okay, sounds good - I'll be closing this for now. Feel free to reopen if you find the issue again.

**Closed by k3d3** 2015-06-25 14:08 UTC
